apiVersion: v1
kind: Service
metadata:
  name: gw-sanity-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gw-sanity-service
  type: ClusterIP
  ports:
    - port: 8080
      name: http
