apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
    - port: 9090
      name: http
      targetPort: 9090
