apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-volclaim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
