apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glooctl-check-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glooctl-check-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: glooctl-check
    namespace: {{ .Release.Namespace }}
