apiVersion: v1
kind: ServiceAccount
metadata:
  name: glooctl-check
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/eks-{{ .Values.app.geo }}-api-role
