apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twistlock-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: service-parameter
    remoteRef:
      key: twistlock
      property: service_parameter

  - secretKey: ca.pem
    remoteRef:
      key: twistlock
      property: ca_cert

  - secretKey: client-cert.pem
    remoteRef:
      key: twistlock
      property: client_cert


  - secretKey: client-key.pem
    remoteRef:
      key: twistlock
      property: client_key

  - secretKey: admission-cert.pem
    remoteRef:
      key: twistlock
      property: admission_cert

  - secretKey: admission-key.pem
    remoteRef:
      key: twistlock
      property: admission_key

  - secretKey: cluster_id
    remoteRef:
      key:  {{ .Values.CLUSTER_SECRET }}
      property: cluster_id


  - secretKey:  cluster
    remoteRef:
      key: {{ .Values.CLUSTER_SECRET }}
      property: cluster_name
