apiVersion: v1
kind: Service
metadata:
  name: volga
  namespace: {{ .Release.Namespace }}
  labels:
    app: volga
spec:
  ports:
  - name: public
    port: 8070
    protocol: TCP
  selector:
    app: volga
  type: ClusterIP
