apiVersion: v1
kind: ConfigMap
metadata:
  name: volgaconfigfiles
data:
  push-config.sh: |
    {{- include "startup" . | indent 4 }}
  source: |
    {{- include "source" . | indent 4 }}
  accounts-jmx: |
    {{- include "accounts" . | indent 4 }}
  numbers-jmx: |
    {{- include "numbers" . | indent 4 }}