local utils = import 'lib/utils.libsonnet';

{
  _routeLibVersion:: 'master',
  gitTags+: {
    'gloo-nexmo-routes'+: {
      'nexmo-admin-dashboard': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-accounts-secrets': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-applications': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-argocd': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-auditevent': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-auth': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-capi': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-conversations': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-conversations-v01': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-conversations-v02': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-conversations-v03': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-conversions': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='30579094da4b2e76901adae59c428eb456fba0b7'),
      'nexmo-cost': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-credentials': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-cs-ips': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-devapi-rest': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-domains-service': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-enforcer-service': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-fd-alerts-generator': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-generic-rate-limiting': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-gloo-errors': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-media': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-messages': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-ni': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-ni-rest': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-numintel-insight': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-partnerapi': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-phub-pools': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-phub-prov': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-push': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      //      'nexmo-rate-limiting-sanity': utils._RouteConfig(activeRevision='master',
      //                                                       activeRouteLibVersion='master',
      //                                                       passiveRevision='APIGW-1424-Block-api_key-in-Gloo-WAF',
      //                                                       passiveRouteLibVersion='APIGW-1424-Block-api_key-in-Gloo-WAF'),
      'nexmo-rate-limiting-sanity': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      //      'nexmo-rate-limiting-sanity': utils._RouteConfig(),
      'nexmo-redact': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-reports': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='DATA-5201_v2b_reports_rate'),
      'nexmo-rtc': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-sms': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-sms-internal': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-tts': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-utilities': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-verify': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-vapi': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='VOICESHIEL-219'),
      'nexmo-tokbox': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='VIDECO-8711-AddViamToAnvil'),
      'nexmo-tokbox-tools': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-tools': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'nexmo-voice-inspector': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      // This breaks sync on use clusters and euw c1. It should only be deployed on clusters with the updated library.
      // 'permission-service': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='PERMISSION-SERVICE-INTEGRATION'),
    },
    'gloo-vcp-routes'+: {
      // This breaks the config. See https://vonage.slack.com/archives/C010C5JKE85/p1713780898148339?thread_ts=1713779343.641809&cid=C010C5JKE85
      // 'vcp-configuration-service': utils._RouteConfig(routeLibVersion=$._routeLibVersion, revision='APICORE-7760-expose-test-namespace-config-service-endpoints'),
      'vcp-whiteboard-api': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-boost': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-camara-oauth': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-camara-api': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-network-api-reg': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-silent-auth': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
      'vcp-number-insight': utils._RouteConfig(routeLibVersion=$._routeLibVersion),
    },
  },
}
