{
 "title": "API Gateway By Pod",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\"},  aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{aws_account=~\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", pod!=\"*\"},  namespace)"
    }
   },
   {
    "name": "containers",
    "label": "containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{aws_account=~\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", namespace=~\"$namespace\",  pod!=\"*\"},  container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "gw-proxy upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (envoy_cluster_upstream_cx_active{account=~\"$aws_account\", cluster_id=~\"$cluster\", region=~\"$region\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", container=~\"$containers\"}) by (container, pod, namespace)",
     "legendFormat": "{{container}}: {{pod}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Total CPU utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (container, namespace) (rate (container_cpu_usage_seconds_total{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", container=~\"$containers\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, pod, namespace) (rate (container_cpu_cfs_throttled_seconds_total{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", container=~\"$containers\"}[1m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU By Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, pod, namespace) (rate (container_cpu_usage_seconds_total{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", container=~\"$containers\"}[1m]))",
     "legendFormat": "{{container}}: {{pod}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{aws_account=~\"$aws_account\", namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", container=~\"$containers\", hostname!=\"\"}",
     "legendFormat": "{{container}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Auth Response By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq{aws_account=~\"$aws_account\", envoy_response_code=\"200\", envoy_cluster_name=~\".*auth.*\", kubernetes_namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"} [1m])) by (kubernetes_pod_name)",
     "legendFormat": "200 - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq{envoy_response_code=\"401\", envoy_cluster_name=~\".*auth.*\", aws_account=~\"$aws_account\", kubernetes_namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"} [1m])) by (kubernetes_pod_name)",
     "legendFormat": "401 - {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq{envoy_response_code!=\"401\", envoy_response_code!=\"200\", envoy_cluster_name=~\".*auth.*\", aws_account=~\"$aws_account\", kubernetes_namespace=~\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"} [1m])) by (kubernetes_pod_name)",
     "legendFormat": "other - {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}