{
 "title": "ArgoCD/Application/Overview",
 "tags": [
  "argo-cd ",
  "ci/cd"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" },
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\"},aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\"},region)"
    }
   },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=\"$aws_account\", region=\"$region\"},cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application Health Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\",\nregion=~'$region',cluster_id=~'$cluster_id',namespace=~\"argocd\",dest_server=~\"https://kubernetes.default.svc\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (region, cluster_id,job, dest_server, project,health_status,name)",
     "legendFormat": "{{ project }}/{{region}}/{{cluster_id}}/{{name}} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\",\nregion=~'$region',cluster_id=~'$cluster_id',namespace=~\"argocd\",dest_server=~\"https://kubernetes.default.svc\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (region, cluster_id,job, dest_server, project,health_status,name, sync_status)",
     "legendFormat": "{{ project }}/{{region}}/{{cluster_id}}/{{name}} - {{sync_status}}"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{aws_account=~\"$aws_account\",\nregion=~'$region',\nnamespace=~'argocd',\ndest_server=~'https://kubernetes.default.svc',\nautosync_enabled!=\"true\"\n  }\n) by (project, autosync_enabled, region, cluster_id ) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications Out Of Sync",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{aws_account=~\"$aws_account\",\nregion=~'$region',\nnamespace=~'argocd',\ndest_server=~'https://kubernetes.default.svc',\nsync_status!=\"Synced\"\n  }\n) by (sync_status, region, cluster_id,project, name) > 0"
    }
   ]
  }
 ]
}