{
 "title": "AWS Global Accelerator Dashboard",
 "tags": [
  "AWS",
  "Global Accelerator "
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "query": "label_values(aws_globalaccelerator_processed_bytes_out_sum, aws_account)"
   },
   {
    "name": "global_accelerator_id",
    "query": "label_values(aws_globalaccelerator_processed_bytes_out_sum, dimension_accelerator)"
   }
  ]
 },
 "panels": [
  {
   "title": "New Flow Count by Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=~\"$global_accelerator_id\"}) by (dimension_accelerator)",
     "legendFormat": "{{dimension_accelerator}} - Active Flows"
    }
   ]
  },
  {
   "title": "Active Flow Count by Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=~\"$global_accelerator_id\"}) by (dimension_accelerator)",
     "legendFormat": "{{dimension_accelerator}} - Active Flows"
    }
   ]
  },
  {
   "title": "Processed Bytes In by Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=~\"$global_accelerator_id\"}) by (dimension_accelerator)",
     "legendFormat": "{{dimension_accelerator}} - Processed Bytes In"
    }
   ]
  },
  {
   "title": "Processed Bytes Out by Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=~\"$global_accelerator_id\"}) by (dimension_accelerator)",
     "legendFormat": "{{dimension_accelerator}} - Processed Bytes Out"
    }
   ]
  }
 ]
}