{
 "title": "PrismaCloud Vulnerabilities",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Refractor UI: [Accounts](https://refractor.main0.api.nexmo.dev.euw1.vonagenetworks.net/accounts) | [Packages](https://refractor.main0.api.nexmo.dev.euw1.vonagenetworks.net/packages) | [Package Attribution](https://refractor.main0.api.nexmo.dev.euw1.vonagenetworks.net/attribution) | [Unique Critical Vulnerabilities](https://refractor.main0.api.nexmo.dev.euw1.vonagenetworks.net/vulns?filter=critical) | [Change Log](https://refractor.main0.api.nexmo.dev.euw1.vonagenetworks.net/changelog.txt) | [ArgoCD App](https://argocd.pl.main0.api.nexmo.dev.euw1.vonagenetworks.net/applications/prisma-refractor?operation=false&orphaned=true&resource=)"
   }
  },
  {
   "title": "Vulnerable packages by account",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg by (scanned_aws_account)(refractor_prisma_scan_vulnerable_packages)",
     "legendFormat": "{{scanned_aws_account}}"
    }
   ]
  },
  {
   "title": "Package Version Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (package)(refractor_multiversion_packages) > 2\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Package Version Vulnerability Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (package, version)(refractor_prisma_pkg_crit_vuln_counts) > 10\n",
     "legendFormat": "{{package}}:{{version}}"
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } }
 ]
}