{
 "title": "AWS Global Accelerator Dashboard - Detailed View",
 "tags": [
  "AWS",
  "Global Accelerator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   },
   {
    "name": "global_accelerator_id",
    "label": "global_accelerator_id",
    "query": {
     "query": "label_values(aws_globalaccelerator_active_flow_count_sum,dimension_accelerator)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New Flow Count by Accelerator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "New Flow Count by Accelerator-IP Adresses - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_accelerator_ipaddress)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "New Flow Count by Accelerator -Endpoint-Group- $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_endpoint_group)\n",
       "legendFormat": "{{dimension_endpoint_group}}"
      }
     ]
    },
    {
     "title": "New Flow Count by Accelerator-Listener - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_listener)\n",
       "legendFormat": "{{dimension_listener}}"
      }
     ]
    },
    {
     "title": "New Flow Count by Accelerator-Source_Region - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_source_region)\n",
       "legendFormat": "{{dimension_source_region}}"
      }
     ]
    },
    {
     "title": "New Flow Count by Accelerator-Transport_Protocol - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_new_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_transport_protocol)\n",
       "legendFormat": "{{dimension_transport_protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Flow Count by Accelerator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Flow Count by Accelerator-IP Adresses - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_accelerator_ipaddress)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Active Flow Count by Accelerator -Endpoint-Group- $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_endpoint_group)\n",
       "legendFormat": "{{dimension_endpoint_group}}"
      }
     ]
    },
    {
     "title": "Active Flow Count by Accelerator-Listener - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_listener)\n",
       "legendFormat": "{{dimension_listener}}"
      }
     ]
    },
    {
     "title": "Active Flow Count by Accelerator-Source_Region - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_source_region)\n",
       "legendFormat": "{{dimension_source_region}}"
      }
     ]
    },
    {
     "title": "Active  Flow Count by Accelerator-Transport_Protocol - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_active_flow_count_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_transport_protocol)\n",
       "legendFormat": "{{dimension_transport_protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processed Bytes In by Accelerator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processed Bytes In by Accelerator-IP Adresses - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_accelerator_ipaddress)",
       "legendFormat": "{{dimension_accelerator_ipaddress}}"
      }
     ]
    },
    {
     "title": "Processed Bytes In by Accelerator -Endpoint-Group- $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_endpoint_group)\n",
       "legendFormat": "{{dimension_endpoint_group}}"
      }
     ]
    },
    {
     "title": "Processed Bytes In by Accelerator-Listener - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_listener)\n",
       "legendFormat": "{{dimension_listener}}"
      }
     ]
    },
    {
     "title": "Processed Bytes In by Accelerator-Source_Region - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_source_region)\n",
       "legendFormat": "{{dimension_source_region}}"
      }
     ]
    },
    {
     "title": "Processed Bytes In by Accelerator-Transport_Protocol - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_in_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_transport_protocol)\n",
       "legendFormat": "{{dimension_transport_protocol}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processed Bytes Out by Accelerator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processed Bytes Out by Accelerator-IP Adresses - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_accelerator_ipaddress)",
       "legendFormat": "{{dimension_accelerator_ipaddress}}"
      }
     ]
    },
    {
     "title": "Processed Bytes Out by Accelerator -Endpoint-Group- $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_endpoint_group)\n",
       "legendFormat": "{{dimension_endpoint_group}}"
      }
     ]
    },
    {
     "title": "Processed Bytes Out by Accelerator-Listener - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_listener)\n",
       "legendFormat": "{{dimension_listener}}"
      }
     ]
    },
    {
     "title": "Processed Bytes Out by Accelerator-Source_Region - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_source_region)\n",
       "legendFormat": "{{dimension_source_region}}"
      }
     ]
    },
    {
     "title": "Processed Bytes Out by Accelerator-Transport_Protocol - $global_accelerator_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "sum(aws_globalaccelerator_processed_bytes_out_sum{aws_account=~\"$aws_account\",region=\"us-east-1\", cluster_id=\"1vapi-1\", dimension_accelerator=\"$global_accelerator_id\"}) by (dimension_transport_protocol)\n",
       "legendFormat": "{{dimension_transport_protocol}}"
      }
     ]
    }
   ]
  }
 ]
}