prometheus-adapter:
  replicas: 1
  nameOverride: custom-metrics-server
  fullnameOverride: custom-metrics-server
  image:
    tag: v0.12.0
    pullPolicy: Always
  
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi

  prometheus:
    port: false
    path: ""

  rules:
    default: true
    existing: custom-metrics-rules-config
