apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  configuration: |
    [mysqld]
    server_id        = 1
    log-bin          = ./binlog
    binlog-ignore-db = mysql
    binlog-ignore-db = performance_schema
    binlog_format    = ROW
    max_binlog_size  = 1M
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    bind_address     = 0.0.0.0
    log_slave_updates
    max_connections=1000

    [client]
    default-character-set=utf8

    [mysql]
