{{- if .Values.testkube_ui.hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.in.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: {{ .Values.testkube_ui.privateControllerClass }}
  name: {{ .Values.testkube_ui.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.testkube_ui.hostname }}
      http:
        paths:
        - backend:
            service:
              name: testkube-api-server
              port:
                number: 8088
          path: /v1
          pathType: Prefix

{{ end}} 
