environment: prod

smokes:
  executors:
    image: 275313334716.dkr.ecr.us-east-1.amazonaws.com/apigw-smoke-tests:d229d6e
  webhooks:
    slackWebhookUrl: https://hooks.slack.com/services/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
    payloadTemplate: '"{\"text\": \":no_smoking: *Smokes Test suite <https://testkube-ui-c2.api0.v1.prd.euw1.vonagenetworks.net/test-suites/{{ .TestSuiteExecution.TestSuite.Name }}/executions/{{ .TestSuiteExecution.Id }}|{{ .TestSuiteExecution.TestSuite.Name }}> finished with `{{ .TestSuiteExecution.Status }}` status*\n{{ range .TestSuiteExecution.ExecuteStepResults }} {{ range .Execute }}{{- if .Execution.TestName -}} - <https://testkube-ui-c2.api0.v1.prd.euw1.vonagenetworks.net/tests/{{ .Execution.TestName }}/executions/{{ .Execution.Id }}|{{ .Execution.TestName }}> ({{ .Execution.Duration }}) - `{{ .Execution.ExecutionResult.Status }}`\n {{ end }} {{ end }} {{ end }}\"}"'
  tests:
    - name: gateway-smokes
      suiteName: gateway-smokes
      schedule: "* * * * *"
      timeOutSecs: 60
      regions:
        - name: euw1
        - name: euc1
        - name: mec1
        - name: use1
        - name: usw2
        - name: apse1
        - name: apse2
        - name: apse3

    - name: gateway-smokes
      suiteName: gateway-smokes-passive
      delay: true
      schedule: "*/5 * * * *"
      timeOutSecs: 60
      regions:
        - name: euw1-passive
        - name: euc1-passive
        - name: mec1-passive
        - name: use1-passive
        - name: usw2-passive
        - name: apse1-passive
        - name: apse2-passive
        - name: apse3-passive

    # - name: ratelimit-smokes
    #   suiteName: ratelimit-smokes
    #   schedule: "*/5 * * * *"
    #   timeOutSecs: 300
    #   regions:
    #     - name: euw1
    #     - name: euc1
    #     - name: mec1
    #     - name: use1
    #     - name: usw2
    #     - name: apse1
    #     - name: apse2
    #     - name: apse3

    # - name: ratelimit-smokes
    #   suiteName: ratelimit-smokes-passive
    #   delay: true
    #   delayTime: 2m
    #   schedule: "*/10 * * * *"
    #   timeOutSecs: 300
    #   regions:
    #     - name: euw1-passive
    #     - name: euc1-passive
    #     - name: mec1-passive
    #     - name: use1-passive
    #     - name: usw2-passive
    #     - name: apse1-passive
    #     - name: apse2-passive
    #     - name: apse3-passive

    # - name: identity-smokes
    #   suiteName: identity-smokes
    #   schedule: "* * * * *"
    #   timeOutSecs: 60
    #   regions:
    #     - name: euw1
    #     - name: euc1
    #     - name: mec1
    #     - name: use1
    #     - name: usw2
    #     - name: apse1
    #     - name: apse2
    #     - name: apse3

    # - name: identity-admin-smokes
    #   suiteName: identity-admin-smokes
    #   schedule: "*/5 * * * *"
    #   timeOutSecs: 120
    #   regions:
    #     - name: euw1
    #     - name: euc1
    #     - name: mec1
    #     - name: use1
    #     - name: usw2
    #     - name: apse1
    #     - name: apse2
    #     - name: apse3
