endpoints:
  - https://gw-euw1.api-eu.dev.v1.vonagenetworks.net/apigw/argocd/api/webhook
  - https://gw-euw1-sanity.api-eu.dev.v1.vonagenetworks.net/apigw/argocd/api/webhook
  - https://gw-use1.api-us.dev.v1.vonagenetworks.net/apigw/argocd/api/webhook
  - https://gw-use1-sanity.api-us.dev.v1.vonagenetworks.net/apigw/argocd/api/webhook
