apiVersion: v1
kind: Service
metadata:
  name: yace-service
  namespace: {{ .Release.Namespace }}
  
spec:
  selector: 
    app: yace
  type: ClusterIP
  ports:
    - port: 5000
      name: http
      targetPort: 5000
