apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-lister
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-lister
subjects:
  - kind: ServiceAccount
    name: identity-config-monitor
    namespace: {{ .Release.Namespace }}
