apiVersion: v1
kind: Service
metadata:
  name: identity-config-monitor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: identity-config-monitor
  type: ClusterIP
  ports:
    - port: 3000
      name: http
