{{ if .Values.identity.enableSsl }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-ssl-cert
  namespace: {{ .Release.Namespace }}
spec:
  duration: "2160h0m0s"
  renewBefore: "360h0m0s"

  secretName: identity-pkcs12
  commonName: "identity.{{ .Release.Namespace }}.svc.cluster.local"

  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - "identity.{{ .Release.Namespace }}.svc.cluster.local"
    - "identity.{{ .Release.Namespace }}"
  usages:
    - server auth
    - data encipherment
    - key agreement
    - digital signature
  issuerRef:
    name: selfsigned-issuer
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: IDENTITY_CERT_PASSWORD
        name: identity-ssl-password
{{ end }}
