{{ if .Values.identity.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: identity-signing-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NEXMO_IDENTITY_RSA_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1IZ0NBUUF3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0VFWVRCZkFnRUJCQnhWcWZtcjI2UG9Qc3J5dEVrNDllNTEKRGsxNXJjZ1diQjNDWGtoZW9Ud0RPZ0FFT1BPbjFkSnl0QWxuYTRlVFdCV0lueFd1ajBINGNxTVQraUFoVUlMLwpTWWZwS3ZOWitQTVI4L1NrQ1g5SnRSUXAxdGUwYlJIOGkxaz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  NEXMO_IDENTITY_RSA_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUU0d0VBWUhLb1pJemowQ0FRWUZLNEVFQUNFRE9nQUVPUE9uMWRKeXRBbG5hNGVUV0JXSW54V3VqMEg0Y3FNVAoraUFoVUlML1NZZnBLdk5aK1BNUjgvU2tDWDlKdFJRcDF0ZTBiUkg4aTFrPQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=

---

apiVersion: v1
kind: Secret
metadata:
  name: identity-db-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NEXMO_IDENTITY_DB_PASSWORD: S2gwb25QaDNlZw==
  NEXMO_IDENTITY_DB_USERNAME: Y29uZmln

---

apiVersion: v1
kind: Secret
metadata:
  name: tokbox-auth-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TOKBOX_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lKaGRHaGxibUZmWVhWMGFGOXBaREVpTENKdVlXMWxJam9pU205b2JpQkViMlVpTENKcFlYUWlPakUxTVRZeU16a3dNako5LkZVOFEyWnVEVlVNLVhDZXNqaDBuWEU2T0hobUJFdTJFY0lWVF9fQWE0Qk0=

---

apiVersion: v1
kind: Secret
metadata:
  name: identity-interservice-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NUMBER_SERVICE_KEY: ajMwOG52MDV2W3duOTNudnZuZW9ucWczcTA0bnZuCg==

---

apiVersion: v1
kind: Secret
metadata:
  name: identity-ssl-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  IDENTITY_CERT_PASSWORD: ajMwOG52MDV2W3duOTNudnZuZW9ucWczcTA0bnZuCg==

---

apiVersion: v1
kind: Secret
metadata:
  name: identity-applications-jwt
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  IDENTITY_APPLICATION_JWT: QmVhcmVyIGV5SnJhV1FpT2lJeU1ERTNNRGd5TXpJeE5ETTFNQ0lzSW1Gc1p5STZJbEpUTWpVMkluMC5leUpxZEdraU9pSmtZV1EyT1RnMU5pMDBZak5oTFRSa05UY3RPVGRrTWkwMU56Vm1ZV1ZsTURRNVlUZ2lMQ0pwWVhRaU9qRTFOamd6T1RBM05qSXNJbk4xWWlJNkltUmxkbUZ3YVNJc0ltbHpjeUk2SW1SbGRpSjkuTUtKYkZtOS1XVk4zRklteHU4MXYyRS0tbThIdVZjRjJSZXRMS3l5TkppOUFMdGdTWTlTazVrNU12cno2dFNCeXg1blBvYXJlVjl1WWY2WjBqSWhuTllJUlJJaEhZb2hYanZTNGZLV3c3U3NZQ1NTOUJiN19oaklYNTQxWGhJV2ZTY0pndmlrWFFpMk9qYS1xTTg3cTNkd2pIOHcxRFJkMFYxUHhKaEZhMUNtOC1xZHY0WnRVS3EzTWM5RTQ2SjVpeEczUXRGTjBsdjNCNTY4ODU4bG1DNHVDVVg1RDJJaHZlYVVhTllYbVVXS0t2ZENEYkotWFVNUE9UTjJrTkRCRHhma3h6bXFWV29aY3N4emkxRjVJTVR6dFhaLXRGd0haWUlVV1VCM01wY3B6aXpGMEtsSnFPcGF4VG44ZlNSZWJ4UDRESkR6UUVEMnFjRlZUbm80SENn
{{ end }}
