{{ if .Values.identity.secret.external }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-db-config
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-db-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Nexmo_Identity_DatabaseCredentials

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-signing-key
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-signing-key
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Nexmo_Identity_SigningKey

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tokbox-auth-token
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: tokbox-auth-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Tokbox_Auth_Token 

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-interservice-secret
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-interservice-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Inter_Service_Key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-ssl-password
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-ssl-password
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Identity_SSL_Certificate_Password

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-applications-jwt
  namespace: nexmo-gateway-services
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: identity-applications-jwt
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Identity_Application_Service_JWT

{{ end }}

