apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
  labels:
    vonage_app: identity
spec:
  ports:
  - name: admin
    port: 4152
    protocol: TCP
  - name: public
    port: 4150
    protocol: TCP
  - name: public-tls
    port: 4160
    protocol: TCP
  - name: debug
    port: 5005
    protocol: TCP
  selector:
    vonage_app: identity
  type: ClusterIP
