{{ if .Values.autoscaler.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity
  minReplicas: {{ .Values.autoscalerConfigs.minReplicas }}
  maxReplicas: {{ .Values.autoscalerConfigs.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscalerConfigs.averageCpu }}
---
{{ end }}
