{{ if .Values.autoscaler.extAuth.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: extauth-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: extauth
  minReplicas: {{ .Values.autoscaler.extAuth.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.extAuth.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.extAuth.averageCpu }}
---
{{ end }}
