apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: license
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo-fed
    gloo: gloo
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: license-key
      remoteRef:
        key: gloo-license-key
        property: license-key
