{{ if .Values.autoscaler.rateLimit.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rate-limit-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rate-limit
  minReplicas: {{ .Values.autoscaler.rateLimit.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.rateLimit.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.rateLimit.averageCpu }}
---
{{ end }}
