apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extauth-signing-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: extauth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: signing-key
      remoteRef:
        key: extauth_signing_key
