dex:
  replicaCount: 1

  image:
    pullPolicy: Always
    tag: "43956db"

  envFrom:
  - secretRef:
      name: testkube-ldap-secret

  envVars:
    - name: "LDAP_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: testkube-ldap-secret
          key: password   
    - name: CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oauth-oauth2-proxy
          key: client-id
    - name: CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oauth-oauth2-proxy
          key: client-secret      

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-privatelink
