global:
  extensions:
    rateLimit:
      deployment:
        extraRateLimitLabels:
          account: 1v-apigw-prod
          aws_account_id: "275313334716"
          region: us-west-2
          cluster_id: 1vapi-1

    extAuth:
      deployment:
        extraExtAuthLabels:
          account: 1v-apigw-prod
          aws_account_id: "275313334716"
          region: us-west-2
          cluster_id: 1vapi-1

clusterName: 1vapi-1
gloo_ui:
  hostname: gloo-ui-c1.api0.v1.prd.usw2.vonagenetworks.net
gloo-ee:
  gloo:
    gateway:
      deployment:
        extraGatewayLabels:
          account: 1v-apigw-prod
          aws_account_id: "275313334716"
          region: us-west-2
          cluster_id: 1vapi-1
    gloo:
      deployment:
        extraGlooLabels:
          account: 1v-apigw-prod
          aws_account_id: "275313334716"
          region: us-west-2
          cluster_id: 1vapi-1
    gatewayProxies:
      gatewayProxy:
        horizontalPodAutoscaler:
          apiVersion: autoscaling/v2
          minReplicas: 6
          maxReplicas: 24
          metrics:
            - type: Pods
              pods:
                metric:
                  name: envoy_cluster_upstream_cx_active
                target:
                  type: AverageValue
                  averageValue: 12000
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 70
        podTemplate:
          extraGatewayProxyLabels:
            account: 1v-apigw-prod
            aws_account_id: "275313334716"
            region: us-west-2
            cluster_id: 1vapi-1
          resources:
            requests:
              cpu: "4"
              memory: "2G"
    rateLimit:
      deployment:
        resources:
          requests:
            memory: "1G"
          limits:
            memory: "1G"
