ingress:
  targetGroupBindings:
    - targetGroupBindingName: nexmo-gw-external-tgb-1vapi-2 # TG for C2 to service ALB
      targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-3:275313334716:targetgroup/api-gw-1vapi-2-M6iCWSNU/62ea591b5f0b64eb
    - targetGroupBindingName: nexmo-gw-external-sanity-tgb-1vapi-2 # TG for C2 to sanity ALB
      targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-3:275313334716:targetgroup/api-gw-1vapi-2-8Mzzd76O/2cd6fa0412af8414

gloo-ee:
  gloo: 
    gatewayProxies:
      gatewayProxy: 
        podTemplate:
          resources:
            requests: 
              cpu: 4           
        kind: 
          deployment:
            replicas: 3
