ingress:
  targetGroupBindings:
    - targetGroupBindingName: nexmo-gw-external-tgb-1vapi-2 # TG for C2 to service ALB
      targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:275313334716:targetgroup/api-gw-1vapi-2-IwKXXEZu/35bdbdb117f0687c
    - targetGroupBindingName: nexmo-gw-external-sanity-tgb-1vapi-2 # TG for C2 to sanity ALB
      targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:275313334716:targetgroup/api-gw-1vapi-2-vAsGxelR/020b70d6181cc6de

gloo-ee:
  gloo: 
    gatewayProxies:
      gatewayProxy: 
        podTemplate:
          resources:
            requests: 
              cpu: 4           
        kind: 
          deployment:
            replicas: 3
