ingress:
  targetGroupBindings:
    - targetGroupBindingName: nexmo-gw-external-tgb-1vapi-2 # TG for C2 to service ALB
      targetGroupARN: arn:aws:elasticloadbalancing:me-central-1:275313334716:targetgroup/api-gw-1vapi-2-UqcZFlUj/0d88907c5ca77927
    - targetGroupBindingName: nexmo-gw-external-sanity-tgb-1vapi-2 # TG for C2 to sanity ALB
      targetGroupARN: arn:aws:elasticloadbalancing:me-central-1:275313334716:targetgroup/api-gw-1vapi-2-OiHKnuS1/8073ac6b7d654c58

gloo-ee:
  gloo: 
    gatewayProxies:
      gatewayProxy: 
        podTemplate:
          resources:
            requests: 
              cpu: 4           
        kind: 
          deployment:
            replicas: 3
