global:
  extensions:
    rateLimit:
      deployment:
        extraRateLimitLabels:
          account: 1v-apigw-qa
          aws_account_id: "507728974998"
          region: us-east-1
          cluster_id: 1vapi-1

    extAuth:
      deployment:
        extraExtAuthLabels:
          account: 1v-apigw-qa
          aws_account_id: "507728974998"
          region: us-east-1
          cluster_id: 1vapi-1

clusterName: 1vapi-1
gloo_ui:
  hostname: gloo-ui-c1.api0.v1.qa.use1.vonagenetworks.net
gloo-ee:
  gloo:
    gateway:
      deployment:
        extraGatewayLabels:
          account: 1v-apigw-qa
          aws_account_id: "507728974998"
          region: us-east-1
          cluster_id: 1vapi-1
    gloo:
      deployment:
        extraGlooLabels:
          account: 1v-apigw-qa
          aws_account_id: "507728974998"
          region: us-east-1
          cluster_id: 1vapi-1
    gatewayProxies:
      gatewayProxy:
        horizontalPodAutoscaler:
          apiVersion: autoscaling/v2
          minReplicas: 1
          maxReplicas: 1
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 70
            - type: Pods
              pods:
                metric:
                  name: envoy_cluster_upstream_cx_active
                target:
                  type: AverageValue
                  averageValue: 12000

        podTemplate:
          extraGatewayProxyLabels:
            account: 1v-apigw-qa
            aws_account_id: "507728974998"
            region: us-east-1
            cluster_id: 1vapi-1

autoscaler:
  rateLimit:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    averageCpu: 70

  extAuth:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    averageCpu: 70
