{
 "title": "All Upstreams",
 "description": "Global overview of Gloo Edge Upstream CRs.",
 "tags": [
  "gloo",
  "dynamic",
  "default"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\"},  aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{kubernetes_namespace=\"$namespace\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# of HTTP requests (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "upstream_rq_total"
    }
   ]
  },
  {
   "title": "HTTP response codes (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Time Heatmap",
   "type": "heatmap",
   "description": "Displays the upstream request times calculated as buckets over 1 minute intervals.  The legend at the bottom left can be used as a guide to understand outliers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Time Quantiles",
   "type": "graph",
   "description": "This chart shows request time quantiles for the upstream in measurements of P99, P95 and P50.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Requests pending...",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_pending_total"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_pending_overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_pending_failure_eject"
    }
   ]
  },
  {
   "title": "Active requests & pending active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
     "legendFormat": "rq_active"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
     "legendFormat": "rq_pending_active"
    }
   ]
  },
  {
   "title": "Requests cancelled and timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_cancelled"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_max_duration_reached{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_max_duration_reached"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_timeout"
    }
   ]
  },
  {
   "title": "Retry counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_retry"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_retry_backoff_ratelimited{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_retry_backoff_ratelimited"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_retry_limit_exceeded{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_retry_limit_exceeded"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_retry_overflow"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_retry_success"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "rq_per_try_timeout"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
     "legendFormat": "{{zone}} ({{host}})"
    }
   ]
  },
  {
   "title": "connection idle timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_idle_timeout{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "cx_idle_timeout"
    }
   ]
  },
  {
   "title": "Upstream Connections by gw-proxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (kubernetes_pod_name, envoy_cluster_name) (envoy_cluster_upstream_cx_active{account=~\"$aws_account\", cluster_id=~\"$cluster\", region=~\"$region\", envoy_cluster_name=~\"$upstream\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate-Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under Limit Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_ratelimit_ok{kubernetes_pod_name!=\"\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", envoy_cluster_name=\"$upstream\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fail Open Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_ratelimit_failure_mode_allowed{kubernetes_pod_name!=\"\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", envoy_cluster_name=\"$upstream\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Over Limit Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_ratelimit_over_limit{kubernetes_pod_name!=\"\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", envoy_cluster_name=\"$upstream\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limit Request Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_ratelimit_error{kubernetes_pod_name!=\"\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", envoy_cluster_name=\"$upstream\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Circuit breaker - connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "circuit open" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_cx_open{envoy_cluster_name=\"$upstream\",app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
       "legendFormat": "CX open"
      }
     ]
    },
    {
     "title": "Circuit Breaker - Retries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_rq_retry_open{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
       "legendFormat": "retry open"
      }
     ]
    },
    {
     "title": "Circuit breaker - requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(envoy_cluster_circuit_breakers_default_rq_open{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"})",
       "legendFormat": "rq open"
      }
     ]
    }
   ]
  },
  {
   "title": "Health checks and Outlier detection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Status (health check)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_health_check_healthy{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}",
       "legendFormat": "Healthy"
      }
     ]
    },
    {
     "title": "Outlier Detection counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(envoy_cluster_outlier_detection_ejections_consecutive_5xx{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])",
       "legendFormat": "ejections_consecutive_5xx"
      },
      {
       "expr": "rate(envoy_cluster_outlier_detection_ejections_total{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m])",
       "legendFormat": "ejections_total"
      }
     ]
    },
    {
     "title": "Health Check failures (rate)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_health_check_failure{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
       "legendFormat": "number of failures"
      },
      {
       "expr": "sum(rate(envoy_cluster_health_check_network_failure{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
       "legendFormat": "network failures"
      }
     ]
    },
    {
     "title": "Number of currently ejected hosts (outlier detection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}",
       "legendFormat": "# of ejected hosts"
      }
     ]
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Upstream Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
       "legendFormat": "IN"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\", aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"}[1m]))",
       "legendFormat": "OUT"
      }
     ]
    }
   ]
  }
 ]
}