{
 "title": "APIGW Upstreams",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[$aws_account][EU-WEST-1][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99, rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-1\", aws_account=~\"$aws_account\", region=\"eu-west-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][EU-WEST-1][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99, rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"eu-west-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][EU-CENTRAL-1][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-1\", aws_account=~\"$aws_account\", region=\"eu-central-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][EU-CENTRAL-1][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"eu-central-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\",  gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][US-EAST-1][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99, rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", kubernetes_namespace=\"nexmo-gloo\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"eu-west-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[5m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}-{{eks_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][US-EAST-1][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"us-east-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][US-WEST-2][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-1\", aws_account=~\"$aws_account\", region=\"us-west-2\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][US-WEST-2][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"us-west-2\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][AP-SE-1][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-1\", aws_account=~\"$aws_account\", region=\"ap-southeast-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][AP-SE-1][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"ap-southeast-1\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][AP-SE-2][1VAPI-1] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-1\", aws_account=~\"$aws_account\", region=\"ap-southeast-2\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "[$aws_account][AP-SE-2][1VAPI-2] Increase in upstreams latency alerts",
   "type": "graph",
   "description": "Increase in upstreams latency alerts (relative to the last 5 days)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99,rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\", cluster_id=\"1vapi-2\", aws_account=~\"$aws_account\", region=\"ap-southeast-2\", envoy_cluster_name !~ \".*nexmo-devapi-rest||.*nexmo-media\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}