{
 "title": "Nexmo Identity Alert",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dependency alerts",
   "type": "graph",
   "description": "Will raise an alert if a dependency of Identity is offline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "identity_numbers_healthy_gauge{aws_account=~\"$aws_account\"}",
     "legendFormat": "Numbers Service - ({{cluster_id}}, {{region}})"
    },
    {
     "expr": "identity_tokbox_healthy_gauge{aws_account=~\"$aws_account\"}",
     "legendFormat": "TokBox - ({{cluster_id}}, {{region}})"
    }
   ]
  },
  {
   "title": "Increase in 401",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (rate(envoy_http_downstream_rq_xx{app=\"gloo\", aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", envoy_response_code_class=\"4\"}[1m])) / sum by (region) (rate(envoy_http_downstream_rq_total{app=\"gloo\", aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\"}[1m]))",
     "legendFormat": "Percentage of 4xx {{environment}} {{region}}"
    }
   ]
  },
  {
   "title": "Increase in Identity Latency",
   "type": "graph",
   "description": "If Identity Latency increases it may indicate that we need more instances or that a backend service is failing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum  (rate(identity_response_timer_seconds_bucket{aws_account=~\"$aws_account\"}[1m])) by (le, region))",
     "legendFormat": "90% Latency {{environment}} : {{region}}"
    }
   ]
  }
 ]
}