{
 "title": "Nexmo Identity",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\", cluster_id=\"$cluster\"},  kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Identity Dependencies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(identity_configdb_healthy_gauge{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "ConfigDB Health"
    },
    {
     "expr": "min(identity_numbers_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "Numbers Health"
    },
    {
     "expr": "min(identity_kafka_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "Kafka Health"
    },
    {
     "expr": "min(identity_tokbox_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "TokBox Health"
    },
    {
     "expr": "min(identity_quota_checker_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "QuotaChecker Health"
    },
    {
     "expr": "min(identity_accounts_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "Accounts Health"
    },
    {
     "expr": "min(identity_applications_healthy_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})",
     "legendFormat": "Applications Health"
    }
   ]
  },
  {
   "title": "Response time for Successful Auth",
   "type": "graph",
   "description": "Response time for Identity requests which resulted in a 200 response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 99%"
    }
   ]
  },
  {
   "title": "Response Time for Identity (Responses above 1s)",
   "type": "graph",
   "description": "The Time taken for identity to respond including responses with duration > 1 second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", le=~\"([1-9]+)\\\\..*\"}[1m])) by(region, le))",
     "legendFormat": "duration >= 1 sec"
    }
   ]
  },
  {
   "title": "Response Time for Cached Auth",
   "type": "graph",
   "description": "The Time taken for identity to respond when the result was cached",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"1\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"1\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"1\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 99%"
    }
   ]
  },
  {
   "title": "Response time for Failed Auth",
   "type": "graph",
   "description": "Response time for Identity requests which didn't result in a 200 response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code!=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code!=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code!=\"200\"}[1m])) by (region, le))",
     "legendFormat": "Response time 99%"
    }
   ]
  },
  {
   "title": "Identity Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "identity_smpp_account_cache_size_gauge{ kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\" }",
     "legendFormat": "Identity Cache Size"
    }
   ]
  },
  {
   "title": "Response Time for DB Auth",
   "type": "graph",
   "description": "The Time taken for identity to respond when the result was cached",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"0\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"0\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(identity_response_timer_seconds_bucket{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\", status_code=\"200\", is_from_cache=\"0\"}[1m])) by (le))",
     "legendFormat": "Cached Response time 99%"
    }
   ]
  },
  {
   "title": "Active DB Pool connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "identity_db_APPS_DB_active_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "APPS_DB_{{pod_name}}"
    },
    {
     "expr": "identity_db_Config_DB_active_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "CONFIG_DB_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Identity Cache Invalidations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(identity_kafka_eviction_counter_total{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})[24h])",
     "legendFormat": "Volga Cache Invalidations"
    }
   ]
  },
  {
   "title": "Idle DB Pool Connections",
   "type": "graph",
   "description": "Idle DB Pool Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "identity_db_Config_DB_idle_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "CONFIG_DB_{{pod_name}}"
    },
    {
     "expr": "identity_db_APPS_DB_idle_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "APPS_DB_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Identity DB Lookups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(identity_smpp_database_lookup_counter_total{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})[24h])",
     "legendFormat": "Identity DB lookups"
    }
   ]
  },
  {
   "title": "Unclosed Orphaned DB Pool Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "identity_db_APPS_DB_unclosed_orphan_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "APPS_DB_{{pod_name}}"
    },
    {
     "expr": "identity_db_Config_DB_unclosed_orphan_connections_all_users_gauge{kubernetes_namespace=\"nexmo-gateway-services\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}",
     "legendFormat": "CONFIG_DB_{{pod_name}}"
    }
   ]
  }
 ]
}