{
 "title": "API Gateways",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\", cluster_id=\"$cluster\"},  kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Healthy upstreams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (envoy_cluster_name) (envoy_cluster_membership_healthy{aws_account=~\"$aws_account\", job=\"kubernetes-pods\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Identity Dependencies Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Healthy Instance" }
     ],
     "targets": [
      {
       "expr": "min(identity_configdb_healthy_gauge{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})[1m]",
       "legendFormat": "ConfigDB Health"
      },
      {
       "expr": "min(identity_numbers_healthy_gauge{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})[1m]",
       "legendFormat": "Numbers Health"
      },
      {
       "expr": "min(identity_kafka_healthy_gauge{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"})[1m]",
       "legendFormat": "Kafka Health"
      }
     ]
    },
    {
     "title": "Percent Response Code per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(envoy_http_downstream_rq_xx{aws_account=~\"$aws_account\", envoy_response_code_class=\"2\",app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) / sum( irate(envoy_http_downstream_rq_total{app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(envoy_http_downstream_rq_xx{aws_account=~\"$aws_account\", envoy_response_code_class=\"4\",app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) / sum( irate(envoy_http_downstream_rq_total{app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(envoy_http_downstream_rq_xx{aws_account=~\"$aws_account\", envoy_response_code_class=\"5\",app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) / sum( irate(envoy_http_downstream_rq_total{app=\"gloo\", job=\"kubernetes-service-endpoints\", envoy_http_conn_manager_prefix=\"http\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) ",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Failed Upstream Health Check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "failures" }
     ],
     "targets": [
      {
       "expr": "sort(count by (envoy_cluster_name) (envoy_cluster_health_check_healthy{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m] < 1))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Envoy latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_proxy_latency_rq_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "req  99% {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_proxy_latency_rq_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "req  95% {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_proxy_latency_rq_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "req  90% {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_proxy_latency_resp_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "resp 99% {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_proxy_latency_resp_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "resp 95% {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_proxy_latency_resp_proxy_latency_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-pods\"}[1m])) by (envoy_cluster_name, le))",
       "legendFormat": "resp 90% {{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Throughput (reqs/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(envoy_http_downstream_rq_total{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", envoy_http_conn_manager_prefix=\"http\"}[1m]))",
       "legendFormat": "Global RPM"
      },
      {
       "expr": "sum (rate(envoy_http_rq_total{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", envoy_http_conn_manager_prefix=\"http\"}[1m]))",
       "legendFormat": "Routed RPM"
      }
     ]
    },
    {
     "title": "Success rate by upstream",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", job=\"kubernetes-pods\", envoy_response_code_class!=\"5\", envoy_cluster_name!=\"metrics_cluster\", kubernetes_namespace=\"$namespace\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) by (envoy_cluster_name)) / (sum (rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", job=\"kubernetes-pods\", envoy_cluster_name!=\"metrics_cluster\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[5m])) by (envoy_cluster_name))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Round Trip time Percentiles",
     "type": "graph",
     "description": "90%, 95%, 99% of total roundtrip time through the gateway",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(envoy_http_downstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", envoy_http_conn_manager_prefix=\"http\", gateway_proxy_id=\"gateway-proxy\"}[1m])) by (le))",
       "legendFormat": "90% {{$namespace}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", envoy_http_conn_manager_prefix=\"http\", gateway_proxy_id=\"gateway-proxy\"}[1m])) by (le))",
       "legendFormat": "95% {{$namespace}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", envoy_http_conn_manager_prefix=\"http\", gateway_proxy_id=\"gateway-proxy\"}[1m])) by (le))",
       "legendFormat": "99% {{$namespace}}"
      }
     ]
    },
    {
     "title": "LoadBalancers statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_active_connection_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "active connections ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_new_connection_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "new connections ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_3_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "3xx elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_4_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "4xx elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_5_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "5xx elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_rejected_connection_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "rejected connections ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_rejected_connection_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "rejected connections ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_500_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "500 elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_502_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "502 elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_503_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "503 elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_504_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "504 elb ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_tg_request_count_sum{aws_account=~\"$aws_account\", name=~\".*:loadbalancer/.*\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "# reqs/min ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_tg_request_count_per_target_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "# reqs/min by target ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_tg_httpcode_target_2_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "2xx by target ({{dimension_load_balancer}},{{dimension_availability_zone}}) "
      },
      {
       "expr": "sum(aws_alb_tg_httpcode_target_3_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer)",
       "legendFormat": "3xx by target ({{dimension_load_balancer}})"
      },
      {
       "expr": "sum(aws_alb_tg_httpcode_target_4_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m])  by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "4xx by target ({{dimension_load_balancer}},{{dimension_availability_zone}})"
      },
      {
       "expr": "sum(aws_alb_tg_httpcode_target_5_xx_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "5xx by target ({{dimension_load_balancer}},{{dimension_availability_zone}})"
      },
      {
       "expr": "sum(aws_alb_tg_target_response_time_average{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "target resp time avg ({{dimension_load_balancer}},{{dimension_availability_zone}}) (ms)"
      },
      {
       "expr": "sum(aws_alb_tg_target_response_time_p95{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "target resp time 95% ({{dimension_load_balancer}},{{dimension_availability_zone}}) (ms)"
      },
      {
       "expr": "sum(aws_alb_tg_target_response_time_p99{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "target resp time 99% ({{dimension_load_balancer}},{{dimension_availability_zone}}) (ms)"
      },
      {
       "expr": "sum(aws_alb_tg_target_connection_error_count_sum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "target conn errors ({{dimension_load_balancer}},{{dimension_availability_zone}}) (ms)"
      }
     ]
    },
    {
     "title": "Upstreams Health Check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(count by (envoy_cluster_name) (envoy_cluster_health_check_healthy{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\",kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m] > 0))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "WAF",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "# Blocked / Counted" }
     ],
     "targets": [
      {
       "expr": "sum(aws_wafv2_counted_requests_sum{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_rule, dimension_web_acl)",
       "legendFormat": "Counted ({{dimension_web_acl}},{{dimension_rule}})"
      },
      {
       "expr": "sum(aws_wafv2_allowed_requests_sum{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_rule, dimension_web_acl)",
       "legendFormat": "Allowed  ({{dimension_web_acl}},{{dimension_rule}})"
      },
      {
       "expr": "sum(aws_wafv2_blocked_requests_sum{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_rule, dimension_web_acl)",
       "legendFormat": "Blocked ({{dimension_web_acl}},{{dimension_rule}})"
      },
      {
       "expr": "sum(aws_wafv2_passed_requests_sum{aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"}[1m]) by (dimension_rule, dimension_web_acl)",
       "legendFormat": "Passed ({{dimension_web_acl}},{{dimension_rule}})"
      }
     ]
    },
    {
     "title": "LoadBalancers health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Healthy" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_tg_healthy_host_count_minimum{aws_account=~\"$aws_account\", tag_kubernetes_io_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", dimension_target_group=~\".*$cluster.*\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "Healthy count ({{dimension_load_balancer}},{{dimension_availability_zone}})"
      },
      {
       "expr": "sum(aws_alb_tg_un_healthy_host_count_maximum{aws_account=~\"$aws_account\", tag_kubernetes_io_service_name=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", dimension_target_group=~\".*$cluster.*\"}[1m]) by (dimension_load_balancer, dimension_availability_zone)",
       "legendFormat": "Unhealthy count  ({{dimension_load_balancer}},{{dimension_availability_zone}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage by Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "alias": "throttling",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum by (container) (rate (container_cpu_usage_seconds_total{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}[1m]))",
       "legendFormat": "{{container}} ({{$namespace}})",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Memory Usage by Container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{aws_account=~\"$aws_account\", image!=\"\", container!=\"POD\", namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}) by (container)",
       "legendFormat": "{{container}} ({{$namespace}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_default_cx_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}: default"
      },
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_high_cx_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}) ",
       "legendFormat": "{{envoy_cluster_name}}: high"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_default_rq_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}: default"
      },
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_high_rq_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}) ",
       "legendFormat": "{{envoy_cluster_name}}: high"
      }
     ]
    },
    {
     "title": "Pending requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_default_rq_pending_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}: default"
      },
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_high_rq_pending_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"}) ",
       "legendFormat": "{{envoy_cluster_name}}: high"
      }
     ]
    },
    {
     "title": "Retry requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_default_rq_retry_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}: default"
      },
      {
       "expr": "sum by (envoy_cluster_name) (envoy_cluster_circuit_breakers_high_rq_retry_open{aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\"})",
       "legendFormat": "{{envoy_cluster_name}}: high"
      }
     ]
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Auth Total Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_internal_upstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"}[1m])) by (le))",
       "legendFormat": "90% auth latency"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_internal_upstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"}[1m])) by (le))",
       "legendFormat": "95% auth latency"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_internal_upstream_rq_time_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"}[1m])) by (le))",
       "legendFormat": "99% auth latency"
      }
     ]
    },
    {
     "title": "Auth response codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_internal_upstream_rq{aws_account=~\"$aws_account\", envoy_response_code=\"200\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"} [1m])) by (envoy_cluster_name)",
       "legendFormat": "200"
      },
      {
       "expr": "sum(increase(envoy_cluster_internal_upstream_rq{aws_account=~\"$aws_account\", envoy_response_code=\"401\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"}  [1m])) by (envoy_cluster_name)",
       "legendFormat": "401"
      },
      {
       "expr": "sum(increase(envoy_cluster_internal_upstream_rq{aws_account=~\"$aws_account\", envoy_response_code!=\"401\", envoy_response_code!=\"200\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", envoy_cluster_name=~\".*auth.*\"} [1m])) by (envoy_cluster_name)",
       "legendFormat": "Other responses"
      }
     ]
    },
    {
     "title": "Identity Response time percentiles (not in use)",
     "type": "graph",
     "description": "90%, 95%, 99% response times from the identity service",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(identity_response_timer_seconds_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"nexmo-gateway-services\", cluster_id=\"$cluster\", region=\"$region\"}[1m])) by (le)) ",
       "legendFormat": "90% {{$namespace}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(identity_response_timer_seconds_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"nexmo-gateway-services\", cluster_id=\"$cluster\", region=\"$region\"}[1m])) by (le)) ",
       "legendFormat": "95% {{$namespace}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(identity_response_timer_seconds_bucket{aws_account=~\"$aws_account\", kubernetes_namespace=\"nexmo-gateway-services\", cluster_id=\"$cluster\", region=\"$region\"}[1m])) by (le)) ",
       "legendFormat": "99% {{$namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "glooe_solo_io_xds_insync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (resource) (increase(glooe_solo_io_xds_insync{aws_account=\"$aws_account\",region=\"$region\",cluster_id=\"$cluster\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "glooe_solo_io_xds_outofsync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (resource) (increase(glooe_solo_io_xds_outofsync{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "glooe_solo_io_xds_total_entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (resource) (increase(glooe_solo_io_xds_total_entities{aws_account=\"$aws_account\",region=\"$region\",cluster_id=\"$cluster\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "glooe_solo_io_xds_nack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (resource) (increase(glooe_solo_io_xds_nack{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}