{
 "title": "API Gateway Upstream Drill-down",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run,  aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{gloo=\"gloo\", aws_account=~\"$aws_account\", cluster_id=\"$cluster\", region=\"$region\"},  kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency by Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_time_bucket|envoy_cluster_external_upstream_rq_time_bucket\",aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "90% - {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_time_bucket|envoy_cluster_external_upstream_rq_time_bucket\", aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "95% - {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_time_bucket|envoy_cluster_external_upstream_rq_time_bucket\", aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m])) by (envoy_cluster_name, le))",
     "legendFormat": "99% - {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Increase in upstreams latency relative to the last 5 days for the 99p",
   "type": "graph",
   "description": "Increase in upstreams latency compared to the last 5 days for the 99p",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stddev(histogram_quantile(0.99, rate({__name__ =~ \"envoy_cluster_external_upstream_rq_time_bucket\",aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", gateway_proxy_id=\"gateway-proxy\", job=\"kubernetes-service-endpoints\"}[1m]))[5d]) by (envoy_cluster_name, le)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "4xx by Upstream",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__ =~ \"envoy_cluster_external_upstream_rq_xx\", envoy_response_code_class=\"4\", envoy_cluster_name!=\"metrics_cluster\", aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", job=\"kubernetes-service-endpoints\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "2xx by Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", envoy_response_code_class=\"2\", envoy_cluster_name!=\"metrics_cluster\", aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", job=\"kubernetes-service-endpoints\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "5xx by upstream",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", envoy_response_code_class=\"5\", envoy_cluster_name!=\"metrics_cluster\", aws_account=~\"$aws_account\", kubernetes_namespace=\"$namespace\", cluster_id=\"$cluster\", region=\"$region\", job=\"kubernetes-service-endpoints\"}[1m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Increase in 5xx per upstream",
   "type": "graph",
   "description": "Increase in 5xx per upstream for all regions relative to the last 24h.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "% of 5xx increase" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_namespace, region, cluster_id, envoy_cluster_name) (rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", envoy_response_code_class=\"5\", envoy_cluster_name!=\"metrics_cluster\", aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\"}[1m])) / sum by(envoy_cluster_name, kubernetes_namespace, region, cluster_id) (rate({__name__ =~ \"envoy_cluster_internal_upstream_rq_xx|envoy_cluster_external_upstream_rq_xx\", envoy_cluster_name!=\"metrics_cluster\", aws_account=~\"$aws_account\", job=\"kubernetes-service-endpoints\"}[6h]))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}