{
 "title": "APIGW ArgoCD",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Application Health",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Healthy\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    },
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Progressing\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    },
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Suspended\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    },
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Missing\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    },
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Degraded\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    },
    {
     "expr": "sum(argocd_app_info{aws_account=~\"$aws_account\", health_status=\"Unknown\"}) by (region, cluster_id) or On() Vector(0)",
     "legendFormat": "{{region}}-{{cluster_id}}: {{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{phase=~\"Error|Failed\"}[$__interval]))) by (phase)"
    }
   ]
  }
 ]
}