{
 "title": "APIGW Cloudwatch Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "aws_account",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run, aws_account)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\"},  region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(gloo_solo_io_setups_run{aws_account=~\"$aws_account\", gloo=\"gloo\", region=\"$region\"},  cluster_id)"
    }
   },
   {
    "name": "alb",
    "label": "alb",
    "query": {
     "query": "label_values(aws_alb_target_response_time_average{aws_account=~\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\"},  dimension_load_balancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WAF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "WAF Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (dimension_web_acl) (aws_wafv2_allowed_requests_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_rule!=\"ALL\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAF Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (dimension_rule, dimension_rule_group, dimension_label_name) (aws_wafv2_blocked_requests_sum{aws_account=\"$aws_account\",region=\"$region\",cluster_id=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Target Response Time Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_target_response_time_average{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Response Time p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_target_response_time_p99{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\",dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Response Time p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_target_response_time_p95{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HttpCode Target 3xx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_target_3_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HttpCode Target 2xx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_target_2_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HttpCode Target 5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_target_5_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HttpCode Target 4xx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_target_4_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client TLS Negotiation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer)(aws_alb_client_tlsnegotiation_error_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_new_connection_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer)(aws_alb_active_connection_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Host Count Minimum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_healthy_host_count_minimum{aws_account=\"$aws_account\",region=\"$region\",cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy host count Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_un_healthy_host_count_maximum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer)(aws_alb_request_count_sum{aws_account=\"$aws_account\", region=\"$region\",cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_target_group!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELB 4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_elb_4_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELB 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by (dimension_load_balancer) (aws_alb_httpcode_elb_5_xx_count_sum{aws_account=\"$aws_account\", region=\"$region\", cluster_id=\"$cluster\", dimension_availability_zone!=\"\", dimension_load_balancer=~\"$alb\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}