{
 "title": "Envoy Proxy Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Gloo control plane",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validation_gateway_solo_io_valid_config",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(envoy_cluster_manager_cds_update_failure{aws_account=\"1v-apigw-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gateway configuration errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_rejected {aws_account=\"1v-apigw-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(envoy_listener_manager_lds_update_failure{aws_account=\"1v-apigw-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream validation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_rejected {aws_account=\"1v-apigw-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route network errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(envoy_http_rds_update_failure{aws_account=\"1v-apigw-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route validation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "envoy_http_rds_update_rejected {aws_account=\"1v-apigw-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}