targetGroupBinding:
    targetGroupARN: "arn:aws:elasticloadbalancing:us-east-1:684154893900:targetgroup/intl-svc-c2-priv-identity-config/9129d9e85b35bab8"

aws:
  ecr:
    repo: 1v-apigw-identity-config-monitor
    tag: latest
