apiVersion: v1
kind: Service
metadata:
  name: argocd-webhook-fan-out
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: argocd-webhook-fan-out
  type: ClusterIP
  ports:
    - port: 3000
      name: http
