apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmagent.fullname" . }}
  namespace: monitoring
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "vmagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vmagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vmagent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            # - "-promscrape.suppressScrapeErrors"
            - "-promscrape.config=/etc/prometheus/prometheus.yml"
            {{- range .Values.victoriaMetrics.endpoints }}
            - "-remoteWrite.url={{ . }}"
            {{- end}}
            - "-remoteWrite.label=cluster_id={{ .Values.clusterName }}"
            - "-remoteWrite.label=cloud_provider=aws"
            - "-remoteWrite.label=aws_account={{ .Values.accountName }}"
            - "-remoteWrite.label=region={{ .Values.region }}"
          ports:
            - name: http
              containerPort: 8429
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: config-volume
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "vmagent.fullname" . }}
          name: config-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
