apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmagent.fullname" . }}
  namespace: monitoring
  labels:
    {{- include "vmagent.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 8429
      targetPort: 8429
      protocol: TCP
      name: http
  selector:
    {{- include "vmagent.selectorLabels" . | nindent 4 }}
