---
replicas: 1
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 68Mi

kube-state-metrics:
  image:
    registry: 684154893900.dkr.ecr.us-east-1.amazonaws.com
    repository: 1v-apigw-kube-state-metrics
  kubeRBACProxy:
    image:
      registry: 684154893900.dkr.ecr.us-east-1.amazonaws.com
      repository: 1v-apigw-kube-rbac-proxy
