---
replicas: 3
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

kube-state-metrics:
  image:
    registry: 275313334716.dkr.ecr.us-east-1.amazonaws.com
    repository: 1v-apigw-kube-state-metrics
  kubeRBACProxy:
    image:
      registry: 275313334716.dkr.ecr.us-east-1.amazonaws.com
      repository: 1v-apigw-kube-rbac-proxy
