apiVersion: v1
kind: Service
metadata:
  name: "consul"
  labels:
    type: 'dependencies'
    serviceName: "consul"
spec:
  type: ClusterIP
  selector:
    app: "consul"
  ports:
    - name: "consul-port"
      port: 7005
      targetPort: 8500
